name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *'  # Ejecuta cada hora
  workflow_dispatch:      # Permite ejecución manual

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install octokit

      - name: Generate stats.html
        run: node get-stats.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit & push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add stats.html
          git commit -m "Update GitHub stats page" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/aircunza/github-readme-stats.git HEAD:main

        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
