name: Test GH_TOKEN

on:
  workflow_dispatch:

jobs:
  test-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check GH_TOKEN length
        run: echo "GH_TOKEN length is ${#GH_TOKEN}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Test GH_TOKEN with GitHub API
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -H "Authorization: token $GH_TOKEN" https://api.github.com/user

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          echo "Update $(date)" > test.txt
          git add test.txt
          git commit -m "Update test file from workflow" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/aircunza/github-readme-stats.git HEAD:main
