name: Generate Stats and Push

on:
  workflow_dispatch:

jobs:
  generate-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false  # importante para controlar el token

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Generate stats HTML
      run: node get-stats.js

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Commit and push stats.html
      run: |
        git add stats.html
        git commit -m "Update stats.html from workflow" || echo "No changes to commit"
        git push origin HEAD:main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
