name: Generate GitHub Stats SVG

on:
  schedule:
    - cron: '0 0 * * *' # Ejecuta todos los días a medianoche UTC
  workflow_dispatch:  # Permite ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Generate SVG stats
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: node generate-stats-svg.js

    - name: Commit and push SVG
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update GitHub stats SVG"
        file_pattern: "docs/stats.svg"
        branch: main
