name: Test Push x

on:
  push:
    branches:
      - main

jobs:
  test-push:
    if: github.actor != 'github-actions[bot]'  # Evita loops
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Create test file
        run: echo "Test $(date)" > test.txt

      - name: Commit and push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add test.txt
          git commit -m "Test push from workflow" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/aircunza/github-readme-stats.git HEAD:main
