name: Test GitHub Token Permissions

on:
  workflow_dispatch:

jobs:
  test-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install octokit

      - name: Run get-stats.js (show stats output)
        run: node get-stats.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run push-test.js (test push permission)
        run: node push-test.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
