name: Update GitHub Stats

on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git config
        run: |
          git config user.name "aircunza"
          git config user.email "aircunza@users.noreply.github.com"

      - name: Generate stats
        run: |
          echo "## 🔥 Stats updated on $(date)" > STATS.md
          echo "" >> STATS.md
          echo "- Total repos: $(curl -s -H "Authorization: token ${GH_TOKEN}" https://api.github.com/users/aircunza | jq '.public_repos')" >> STATS.md
          echo "- Followers: $(curl -s -H "Authorization: token ${GH_TOKEN}" https://api.github.com/users/aircunza | jq '.followers')" >> STATS.md
          echo "- Following: $(curl -s -H "Authorization: token ${GH_TOKEN}" https://api.github.com/users/aircunza | jq '.following')" >> STATS.md

      - name: Commit & push if changed
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add STATS.md
          git commit -m "📊 Update GitHub stats" || echo "No changes to commit"
          git push
