name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *'  # cada hora, por ejemplo
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install octokit

      - name: Generate stats.html
        run: node get-stats.js
        env:
          GH_PAT_READ: ${{ secrets.GH_PAT_READ }}

      - name: Commit & push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add stats.html
          git commit -m "Update GitHub stats page" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GH_PAT_WRITE}@github.com/aircunza/github-readme-stats.git
          git push origin HEAD:main
        env:
          GH_PAT_WRITE: ${{ secrets.GH_PAT_WRITE }}
