name: test-push

on:
  workflow_dispatch:

jobs:
  push-test:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Modify test file
        run: echo "updated on $(date)" > test.txt

      - name: Git config
        run: |
          git config user.name "aircunza"
          git config user.email "your_email@example.com"

      - name: Set up PAT authentication
        run: git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}

      - name: Commit and push
        run: |
          git add test.txt
          git commit -m "Update test.txt from workflow" || echo "Nothing to commit"
          git push origin HEAD:main
