name: Generate GitHub Stats Badge

on:
  schedule:
    - cron: "0 0 * * *" # Corre cada día a medianoche
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # clave para usar GH_TOKEN personalizado

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Generate stats SVG
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npm run generate-stats

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add stats.svg
        git commit -m "Update GitHub stats [skip ci]" || echo "No changes to commit"
        git push
