name: Generate and Publish Stats SVG

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Diario a medianoche (opcional)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false  # Muy importante para usar token custom

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install octokit

    - name: Generate stats SVG
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: node get-stats.js

    - name: Commit and push SVG
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/stats.svg
        git commit -m "Update stats SVG [skip ci]" || echo "No changes to commit"
        git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
