name: Test Push with PAT

on:
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show GH_TOKEN length
        run: echo "GH_TOKEN length is ${#GH_TOKEN}"

      - name: Test GitHub API with PAT
        run: "curl -H \"Authorization: token $GH_TOKEN\" https://api.github.com/user"
        
      - name: Make a test change and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          echo "Update $(date)" > test.txt
          git add test.txt
          git commit -m "Update test file from workflow" || echo "No changes to commit"

          echo "Setting remote with PAT token"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/aircunza/github-readme-stats.git

          echo "Current remotes:"
          git remote -v

          git push origin main
