name: Generate GitHub Stats

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Evita bucles con commits del workflow

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./  # Ajusta si tu package.json está en otra carpeta

      - name: Run get-stats script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: node get-stats.js
        working-directory: ./  # Ajusta si el script está en otra carpeta

      - name: Commit and push stats file(s)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add stats.html docs/stats.svg || echo "No new files to commit"
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update GitHub stats [skip ci]"
            git push
          fi
