name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Corre todos los días a medianoche UTC
  workflow_dispatch:    # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install octokit

      - name: Run stats script
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: node get-stats.js

      - name: Commit and push stats.html
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull origin main --rebase || true
          git add stats.html
          git commit -m "Update GitHub stats page" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} HEAD:main
